/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package plugins

/*
Prefix Cache Plugin Design

Overview:
The Prefix Cache Plugin is a scoring plugin for the kthena router scheduler that implements a prefix-based matching mechanism
for model inference requests. It helps optimize pod scheduling by identifying pods that have previously processed similar
prompts, potentially improving inference performance through cache hits.

Key Components:

1. PrefixCache
   - Main plugin struct implementing the framework.ScorePlugin interface
   - Manages the caching mechanism for model inference requests
   - Configurable parameters for block size and maximum blocks to match

2. ModelPrefixStore
   - Three-level map structure: model -> hash -> pod
   - The LRU cache is used to record hashes. The evicted hash will also be remove from the three-level map above synchronously.
   - During the matching process, only the topK pods with the longest matching prefixes will be returned.

Core Features:

1. Prefix Matching
   - Divides prompts into fixed-size blocks (default: 64 bytes)
   - Generates rolling hashes for each block using xxHash algorithm
   - Each hash is generated by combining the previous block's hash with the current block's content
   - This creates a chain of dependencies where each hash implicitly contains information about all previous blocks
   - When matching hashes, we can start from the end and work backwards:
     * If a hash matches, it guarantees that all previous blocks also match
     * This property allows for efficient prefix matching without checking each block individually
     * The matching length is determined by the position of the first matching hash

2. Scoring Mechanism
   - Scores pods based on the length of matching prefixes
   - Score range: 0-100, calculated as (matching blocks / total blocks) * 100
   - Higher scores indicate better cache hit potential

3. Cache Management
   - LRU-based eviction policy for memory efficiency
   - Automatic cleanup of evicted entries
   - Configurable cache capacity and top-K results

Usage:
The plugin is used in the kthena router scheduler framework to score pods based on their potential
for cache hits. It's particularly useful for inference workloads where similar prompts are
likely to be processed multiple times.

Configuration Parameters:
- BlockSizeToHash: Size of each block for hashing (default: 64 bytes)
- MaxBlocksToMatch: Maximum number of blocks to process (default: 128), longer prompts are not processed
- Cache capacity and top-K results are configurable (default: 50000 and 5 respectively)

*/

import (
	"fmt"

	"github.com/cespare/xxhash"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/klog/v2"
	"sigs.k8s.io/yaml"

	"github.com/volcano-sh/kthena/pkg/kthena-router/datastore"
	"github.com/volcano-sh/kthena/pkg/kthena-router/metrics"
	"github.com/volcano-sh/kthena/pkg/kthena-router/scheduler/framework"
	"github.com/volcano-sh/kthena/pkg/kthena-router/scheduler/plugins/cache"
	"github.com/volcano-sh/kthena/pkg/kthena-router/utils"
)

const PrefixCachePluginName = "prefix-cache"

const (
	defaultPrefixCacheBlockSizeToHash  = 64
	defaultPrefixCacheMaxBlocksToMatch = 128
	defaultPrefixCacheMaxHashCacheSize = 50000
	defaultPrefixCacheTopKMatches      = 5
)

var _ framework.ScorePlugin = &PrefixCache{}
var _ framework.PostScheduleHook = &PrefixCache{}

type PrefixCache struct {
	name string

	blockSizeToHash  int
	maxBlocksToMatch int
	store            *cache.ModelPrefixStore
}

type PrefixCacheArgs struct {
	BlockSizeToHash  int `yaml:"blockSizeToHash,omitempty"`
	MaxBlocksToMatch int `yaml:"maxBlocksToMatch,omitempty"`
	MaxHashCacheSize int `yaml:"maxHashCacheSize,omitempty"`
	TopKMatches      int `yaml:"topKMatches,omitempty"`
}

// Default token block size of vLLM is 16, and a good guess of average characters per token is 4.
// So we use 64 as the default block size.
func NewPrefixCache(store datastore.Store, pluginArg runtime.RawExtension) *PrefixCache {
	prefixCacheArgs := PrefixCacheArgs{
		BlockSizeToHash:  defaultPrefixCacheBlockSizeToHash,
		MaxBlocksToMatch: defaultPrefixCacheMaxBlocksToMatch,
		MaxHashCacheSize: defaultPrefixCacheMaxHashCacheSize,
		TopKMatches:      defaultPrefixCacheTopKMatches,
	}

	if len(pluginArg.Raw) > 0 {
		if err := yaml.Unmarshal(pluginArg.Raw, &prefixCacheArgs); err != nil {
			klog.Errorf("Failed to unmarshal PrefixCacheArgs, using default values: %v", err)
			prefixCacheArgs = PrefixCacheArgs{
				BlockSizeToHash:  defaultPrefixCacheBlockSizeToHash,
				MaxBlocksToMatch: defaultPrefixCacheMaxBlocksToMatch,
				MaxHashCacheSize: defaultPrefixCacheMaxHashCacheSize,
				TopKMatches:      defaultPrefixCacheTopKMatches,
			}
		}
	}
	if prefixCacheArgs.BlockSizeToHash <= 0 {
		prefixCacheArgs.BlockSizeToHash = defaultPrefixCacheBlockSizeToHash
	}
	if prefixCacheArgs.MaxBlocksToMatch <= 0 {
		prefixCacheArgs.MaxBlocksToMatch = defaultPrefixCacheMaxBlocksToMatch
	}
	if prefixCacheArgs.MaxHashCacheSize <= 0 {
		prefixCacheArgs.MaxHashCacheSize = defaultPrefixCacheMaxHashCacheSize
	}
	if prefixCacheArgs.TopKMatches <= 0 {
		prefixCacheArgs.TopKMatches = defaultPrefixCacheTopKMatches
	}

	p := &PrefixCache{
		name: PrefixCachePluginName,

		blockSizeToHash:  prefixCacheArgs.BlockSizeToHash,
		maxBlocksToMatch: prefixCacheArgs.MaxBlocksToMatch,
	}
	p.store = cache.NewModelPrefixStore(store, prefixCacheArgs.MaxHashCacheSize, prefixCacheArgs.TopKMatches)
	metrics.DefaultMetrics.SetPrefixCacheEntriesProvider(p.store.EntryCount)
	return p
}

func (p *PrefixCache) Name() string {
	return p.name
}

// matchRatio returns matched/total as a fraction in [0,1], or 0 when total is 0.
func matchRatio(matched, total int) float64 {
	if total <= 0 {
		return 0
	}
	return float64(matched) / float64(total)
}

// Score 对每个候选 Pod 打 prefix-cache 命中分 [0,100]。
//
// 原理: prompt 被切成固定块(默认64字节), 每块算一个滚动哈希(见 hashPrompt)。
// 哈希链的特性 — 命中第 k 个哈希就保证前 k 块全部相同(前缀匹配)。
// store.FindTopMatches 返回每个 Pod 最长匹配到第几个块(matchLen), 不匹配的 Pod 不在 map 里。
//
// 打分公式: score = matchLen / totalHashes × 100
//   即"Pod 缓存住的前缀占 prompt 总块数的比例"。完全命中=100, 不命中=0。
//   越高分 → 该 Pod 越可能已缓存这个 prompt 的前缀, 调度过去能省 prefill 计算。
//
// 副作用: 把 hashes 写回 ctx.Hashes, 供 PostSchedule 阶段把本次 prompt 哈希写入缓存。
//   这样下次同前缀请求来时, 这个 Pod 就能命中(正反馈)。
func (p *PrefixCache) Score(ctx *framework.Context, pods []*datastore.PodInfo) map[*datastore.PodInfo]int {
	// Hash the prompt
	hashes := p.hashPrompt(ctx.Model, utils.GetPromptString(ctx.Prompt))
	if len(hashes) == 0 {
		return nil
	}

	// Store hashes in context for later use in PostSchedule
	ctx.Hashes = hashes

	// Find pods with matching prefixes: returns map[NamespacedName]matchLen for topK pods.
	matchByName := p.store.FindTopMatches(ctx.Model, hashes, pods)

	// Single pass over pods: score = cache-hit score if found, 0 otherwise.
	totalHashes := len(hashes)
	longestMatch := 0
	scoreResults := make(map[*datastore.PodInfo]int, len(pods))
	for _, pod := range pods {
		nsName := pod.GetPodNamespacedName()
		if matchLen, ok := matchByName[nsName]; ok {
			// 命中: 按匹配块数占比打分
			scoreResults[pod] = int((float64(matchLen) / float64(totalHashes)) * 100)
			if matchLen > longestMatch {
				longestMatch = matchLen
			}
		} else {
			// 未命中: 0 分
			scoreResults[pod] = 0
		}
	}

	if ctx.MetricsRecorder != nil {
		// 记录最佳匹配 Pod 的命中率指标 (longestMatch/total), 0 表示完全 miss
		ctx.MetricsRecorder.RecordPrefixCacheMatchRatio(matchRatio(longestMatch, totalHashes))
	}

	return scoreResults
}

// PostSchedule 在请求代理成功后, 把本次 prompt 的哈希链写入缓存 (正反馈)。
//
// 为什么需要: Score 只读缓存判命中, 但新 prompt 的哈希不会被任何 Pod 记住。
// 必须在请求实际打到某 Pod 后, 把这个 prompt 的哈希"记到"该 Pod 名下,
// 下次同前缀的请求来时 Score 就能命中该 Pod。
//
// index 是本次代理在 TopN 列表中的位置:
//   同构: ctx.BestPods[index] 是实际承接请求的 Pod
//   PD分离: ctx.DecodePods[index] + ctx.PrefillPods[index] 都要记 (decode/prefill 各自缓存)
func (p *PrefixCache) PostSchedule(ctx *framework.Context, index int) {
	if ctx.BestPods != nil {
		// 同构模式: 把本次 prompt 哈希链记到实际承接的 Pod 名下
		p.store.Add(ctx.Model, ctx.Hashes, ctx.BestPods[index])
		return
	}

	// PD 分离模式: decode 和 prefill 分别记录 (各自可能缓存不同部分的前缀)
	if index < len(ctx.DecodePods) && ctx.DecodePods[index] != nil && len(ctx.Hashes) > 0 {
		p.store.Add(ctx.Model, ctx.Hashes, ctx.DecodePods[index])
	}

	if index < len(ctx.PrefillPods) && ctx.PrefillPods[index] != nil && len(ctx.Hashes) > 0 {
		p.store.Add(ctx.Model, ctx.Hashes, ctx.PrefillPods[index])
	}
}

func (p *PrefixCache) hashPrompt(model string, prompt string) []uint64 {
	res := []uint64{}
	if len(prompt) == 0 {
		return res
	}

	// Initialize first block hash
	// Use model name as the first hash to avoid hash collision
	var prevHash uint64 = xxhash.Sum64([]byte(model))
	blockStart := 0

	// Process blocks up to maxBlocksToMatch or until we run out of prompt
	for i := 0; i < p.maxBlocksToMatch && blockStart < len(prompt); i++ {
		// Calculate end position for current block
		blockEnd := blockStart + p.blockSizeToHash
		if blockEnd > len(prompt) {
			blockEnd = len(prompt)
		}

		// Get current block content and combine with previous hash
		block := prompt[blockStart:blockEnd]
		data := []byte(fmt.Sprintf("%d%s", prevHash, block))

		// Use xxHash algorithm
		currHash := xxhash.Sum64(data)

		// Append hash to results
		res = append(res, currHash)

		// Update for next iteration
		prevHash = currHash
		blockStart = blockEnd

		// Break if we've reached the end of prompt
		if blockEnd == len(prompt) {
			break
		}
	}

	return res
}
